### ISSUE TITLE
Detect Done vs. Pause

### ISSUE THREAD

**Issue by BrettKoenig** [brandly/angular-youtube-embed#134]
I was listening to the event youtube.player.paused and realized this event gets fired when the user hits both the done button and the pause button. I'm testing on mobile. Is there a way to detect the difference, or detect when the player is fullscreen and not fullscreen?

Thanks

**Comment by brandly** [comment]
hey!

i'm not sure what "the done button" you mentioned is, but i'm under the impression that `paused` fires whenever the player goes from playing to not playing, no matter what caused it. there's an `ended` event that fires when the video has played to completion.

really, all these events are defined by the official YouTube embed API. [you can read about them here.](https://developers.google.com/youtube/iframe_api_reference#Events)

looking through those docs, i don't see any way to detect if the player is fullscreen or not. it might be worth perusing those docs though, since there might be a way to build whatever you're trying to build given the methods they do provide.

let me know if there's anything else i can clear up! sorry i don't have a more direct answer to your question! 🌟
