### ISSUE TITLE
Remain in fullscreen when playing next video

### ISSUE THREAD

**Issue by snobear** [brandly/angular-youtube-embed#41]
Thanks for the great directive.  I'm building an app that will load a new video when the current video ends.  If I'm watching a video in fullscreen on a desktop, the fullscreen is exited when the next video is played.  This is the behavior on Chrome, Firefox, and IE from what I've tested.

Any idea how to keep the player in fullscreen so its a continuous fullscreen experience?  I've got my own internal playlist system, so I'd rather not make use of YouTube's playlist system.  

Here's my setup:

**app.html**

```
<div class="embed-responsive embed-responsive-16by9">
  <youtube-video class="embed-responsive-item" video-id="myVideo" player-vars="playerVars">  </youtube-video>
</div>
```

**app.js**

```
scope.playerVars = {
  modestbranding: 1,
  autohide: 1,
  showinfo: 0,
  controls: 1,
  // note: autoplay does not work on most mobile browsers
  autoplay: 1,
  fs: 1,
  allowfullscreen: 1
};

scope.$on('youtube.player.ended', function (event, player) {
  scope.playNext();
});

scope.playNext = function() {
  scope.myVideo = scope.next_youtube_video_id;                                              
}
```

This is probably more of a general youtube API or browser question, but figured you all would have some ideas.

**Comment by brandly** [comment]
hey! i built [this thing](http://redditel.ly/), which is actually how this directive got started, and i've tried doing exactly what you're describing.

unfortunately, i don't think we can do this on the front end. essentially, as a security issue, there's no way to force people into fullscreen, since that kind of steps outside the bounds of the browser. when you change the video, it needs to create a brand new `player`, so even if the previous video was fullscreen, you need explicit user action to make the new one fullscreen.

i think your best option is to make the video the full size of the browser, which [isn't too hard](https://github.com/brandly/angular-youtube-embed#player-size).

depending on how much effort you're putting in to this, you could potentially try automating the creation of YouTube playlists via an API or something, since if you're in a playlist and the user made the video fullscreen, it'll continue to the next video still in fullscreen mode.

best of luck

**Comment by snobear** [comment]
@brandly awesome, thanks for the info! That aligns with what I'm seeing and have read on it.  A YouTube playlist would be perfect, but I'm planning on having Vimeo as another source of videos, so that makes it basically impossible to keep it fullscreen.  Thanks for confirming my suspicions though.
