### ISSUE TITLE
Player is never destroyed

### ISSUE THREAD

**Issue by jdreetz** [brandly/angular-youtube-embed#49]
https://github.com/brandly/angular-youtube-embed/blob/master/src/angular-youtube-embed.js#L190

Checks if player has non-existent property 'd' before destroying and re-adding player. Thus, the player is never re-added. 

```angular-youtube-embed.js
function loadPlayer () {
                if (scope.videoId || scope.playerVars.list) {
                    if (scope.player && scope.player.d &&
                        typeof scope.player.destroy === 'function') {
                        scope.player.destroy();
                    }

                    scope.player = createPlayer();
                }
            };
```

**Comment by rramdat-i** [comment]
Confirmed, player started working as expected after removing `scope.player.d` check

**Comment by CptCompiler** [comment]
what is scope.player.d ?? I thought it was a misspell. And should be scope.player.id  ??!! I Changed it to "id" and it worked again.

**Comment by jdreetz** [comment]
My assumption was that the conditional was checking whether player.destroy was defined before calling it. Somehow scope.player.d got added by mistake?

**Comment by CptCompiler** [comment]
Hmm.... I assumed that if scope.player.id exists that the player was definitely created at some point because the id is set in the create function.
Anyway, I had a look at the properties of the player object (returned by the youtube api) today and there is a property "d" with all the custom properties inside. 

Now I changed scope.player.id back to scope.player.d and its working again. 
I am a little bit confused.

**Comment by brandly** [comment]
it seemed to be a deliberate change that fixed a couple previous issues, so i'm really not sure what's up: https://github.com/brandly/angular-youtube-embed/pull/16
