### ISSUE TITLE
youtube.player.playing event doesn't fire on Firefox

### ISSUE THREAD

**Issue by Lexa1983** [brandly/angular-youtube-embed#54]
Firefox version 37.0.2

www.youtube.com/iframe_api script included in HEAD
angular-youtube-embed.min.js and other scripts are included at the end of BODY

**Comment by brandly** [comment]
could you try this out? http://plnkr.co/edit/HGlRcsT2okJ6BiYUjpdX?p=preview

click play on the video and let me know if you see `playing!!!` in your console

thanks

**Comment by Lexa1983** [comment]
This is what I see in FF console (no playing event, in Chrome can see that event, thanks):

This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More]

Error: WebGL: getParameter: parameter: invalid enum value <enum 0x9246>

Use of getAttributeNode() is deprecated. Use getAttribute() instead.

**Comment by brandly** [comment]
on firefox v38.0.1, i see those errors you mentioned, but they're coming from inside YouTube's official library, which i have no control of

in the middle of those errors, i also see `playing!!!`, so the event is firing

since there are tons of those `This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More]`, are you sure you're not overlooking the `playing!!!`? could you change the `console.log` to an `alert` to verify?

thanks again

**Comment by Lexa1983** [comment]
I've checked it again, after clear browser cache (js, css etc.) - works.
Thank you for help!

**Comment by brandly** [comment]
glad it's working!
