### ISSUE TITLE
Angular 1.4.2 nothing happens

### ISSUE THREAD

**Issue by Undefitied** [brandly/angular-youtube-embed#60]
Nothing happens using:
```
<youtube-video video-id="sMKoNBRZM1M"></youtube-video>
```

and using video-url occurs an <a href="https://docs.angularjs.org/error/$interpolate/noconcat?p0=https:%2F%2Fwww.youtube.com%2Fembed%2Fvideoseries%3Flist%3D%7B%7BselectedCourse.youtube%7D%7D">error</a>

```
<youtube-video video-url="anotherGoodOne"></youtube-video>
```

**Comment by brandly** [comment]
in your first example, use `<youtube-video video-id="'sMKoNBRZM1M'"></youtube-video>`. note the single quotes around `sMKoNBRZM1M`. angular will evaluate whatever you put there, and you want it to be evaluated as a string. without the quotes, it will be treated as an undefined variable on `$scope`.

in the second example, i'm not sure what value you've given `anotherGoodOne`. define it with a URL that looks like [one of these](https://github.com/brandly/angular-youtube-embed/blob/master/test/unit/get-id-from-url.coffee), and it should work. let me know if you find a YouTube link to a video that doesn't work with this directive.

on my local machine, i tried running [the demo](http://brandly.github.io/angular-youtube-embed/#/) with `v1.4.2`, and everything seems to be working!

if you have any more trouble, let me know! i'm gonna close this issue tho, since it looks like the directive is working well with `v1.4.2`. :star2:
