### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided does not match the recipient window's origin

### ISSUE THREAD

**Issue by 4z5lz** [brandly/angular-youtube-embed#62]
Hi,
First of all, very nice directive! Good job!

Sometimes, I get error "Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ..."

How can I solve it?

Thanks

**Comment by brandly** [comment]
hey! i've seen this error before and never worried about it, since everything seemed to function fine

however, it looks [here](http://stackoverflow.com/questions/27573017/failed-to-execute-postmessage-on-domwindow-https-www-youtube-com-http) like it's an issue with mixing `http` and `https` requests

are you using `https://www.youtube.com/iframe_api` over `https` or `http`? it looks like `http` will cause that error to be thrown

let me know!

**Comment by 4z5lz** [comment]
I'm using https

**Comment by karan-kapoor90** [comment]
Any solution on this? I'm facing the same issue, and I think as a result of that, the embeded youtube player doesn't play
