### ISSUE TITLE
Turning off related videos. 

### ISSUE THREAD

**Issue by masscreation** [brandly/angular-youtube-embed#66]
I've tried to concatenate video-id with a variable that contains the string "?rel=0" so as to turn off the related videos (e.g. "http://youtube.com/embed/NVl_IFepdLQ?rel=0")  , but "?enablejsapi=1&origin=http%3A%2F%2Flocalhost%3A3000" gets appended to the url causing the related videos to fire. Is there another way to turn off the related videos?

**Comment by brandly** [comment]
hey! instead of adding `rel=0` to the URL, use [player parameters](https://github.com/brandly/angular-youtube-embed#player-parameters) with something like

```js
$scope.playerVars = {
    rel: 0
};
```

here's a [full list of available parameters](https://developers.google.com/youtube/player_parameters?hl=en)

let me know if you get it working! :star2:

**Comment by masscreation** [comment]
Works perfectly! Thank you! I tried it before, but forgot to add   <pre>player-vars="playerVars"</pre>  back into my html.
