### ISSUE TITLE
Webpack integration

### ISSUE THREAD

**Issue by okhomenko** [brandly/angular-youtube-embed#70]
Package doesn't work with webpack.
On build it throws 
```
WARNING in ./~/angular-youtube-embed/src/angular-youtube-embed.js
Critical dependencies:
1:16-23 require function is used in a way in which dependencies cannot be statically extracted
```

**Comment by brandly** [comment]
[here's when the `require` was added](https://github.com/brandly/angular-youtube-embed/commit/28490e7b0a83cf4ae770a41453fa1081f43df2d4). @konsumer might want to give his input on how best to handle this, since [we were under the impression this would work with webpack](https://github.com/brandly/angular-youtube-embed/pull/56#discussion_r35288888), but maybe we never tried it out hahah

**Comment by okhomenko** [comment]
Yes, now it works fine with webpack. Previous code could work with systems which don't do static analysis (not sure if there are any).

**Comment by brandly** [comment]
#72
