### ISSUE TITLE
CSS deprecation issues

### ISSUE THREAD

**Issue by diegoaguilar** [brandly/angular-youtube-embed#77]
Everytime I load the site where the directive is placed I can see this:
```
GET chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js net::ERR_FAILEDmj @ www-embed-player-new.js:153lj @ www-embed-player-new.js:152kj @ www-embed-player-new.js:152pj @ www-embed-player-new.js:154ml @ www-embed-player-new.js:209yo @ www-embed-player-new.js:304Gq @ www-embed-player-new.js:343(anonymous function) @ sMKoNBRZM1M?enablejsapi=1&origin=http%3A%2F%2Flocalhost%3A9248:10
html5player-new.js:310 SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.
www-embed-player-new.js:153 GET chrome-extension://dliochdbjfkdbacpmhlcpmleaejidimm/cast_sender.js net::ERR_FAILEDmj @ www-embed-player-new.js:153lj @ www-embed-player-new.js:152(anonymous function) @ www-embed-player-new.js:152c.onerror @ www-embed-player-new.js:153
VM4294:1 'webkitMovementX' is deprecated. Please use 'movementX' instead.
```

Should I concern about it?

**Comment by brandly** [comment]
the `cast_sender.js` line has to do with the underlying youtube library looking for a chromecast extension: https://github.com/brandly/angular-youtube-embed/issues/67

all these issues are related to `https://www.youtube.com/iframe_api`, which i have no control over. since google runs youtube, if you're developing a chrome extension, i bet google will keep everything working :smile: 

there's a lot in that library for supporting all kinds of browsers tho, so i bet they keep things around, even when deprecated, to support older browsers. i wouldn't worry about it :rainbow:
