### ISSUE TITLE
Change player size

### ISSUE THREAD

**Issue by diegoaguilar** [brandly/angular-youtube-embed#78]
I tried following jade markup

```jade
.embed-responsive.embed-responsive-16by9
  youtube-video(video-id='currentVideoId' player='youtubePlayer' player-width="'100%'" player-height="'504px'").embed-responsive-item
```

Also tried changing the width for 896px. Player size is not changing, how should I set it up?

**Comment by brandly** [comment]
you're probably running into a conflict, since those `embed` classes are trying to set the `width` and `height` of the player. setting `player-width` and `player-height` should work fine. they're really just [a convenient way to call `player.setSize`](https://github.com/brandly/angular-youtube-embed/blob/d654e43da6da39e07bdd96a85664993da63a2ac6/src/angular-youtube-embed.js#L236-L240)

instead of inlining a string, you can also have a variable like

```js
$scope.width = '100%'
$scope.height = '504px'
```
```jade
youtube-video(video-id='currentVideoId' player='youtubePlayer' player-width="width" player-height="height")
```

**Comment by diegoaguilar** [comment]
It didn't work assigning it to $scope variables

**Comment by brandly** [comment]
if you provide a jsfiddle example of the issue, i'd be happy to look
