### ISSUE TITLE
discourage bower usage?

### ISSUE THREAD

**Issue by Travo100** [brandly/angular-youtube-embed#92]
Hello there,

I saw that you are discouraging bower usage of this directive, and I'm just wondering why so? Also, if we would still like to use bower, how would we go about this? 

Thanks!

**Comment by brandly** [comment]
part of this is just my own personal preference. i think npm is great. i've had unpleasant experiences with bower.

there was also an announcement that development on bower had stopped, which is when i started discouraging use here. however, since then, they announced that people are working on bower again.

soooooo who knows what'll happen in the future. you won't find me using bower, but you're more than welcome to do so :smile: 

```shell
$ bower install --save angular-youtube-mb
```

**Comment by Travo100** [comment]
Thanks for your quick response. Hopefully bower sticks around, I use it quite a bit, and find it really helps streamline my process.

**Comment by scoopstalk** [comment]
$ npm install --save angular-youtube-embed
npm WARN package.json youtubevideo@1.1.1 No repository field.
npm WARN package.json youtubevideo@1.1.1 No README data
npm WARN package.json youtubevideo@1.1.1 No license field.
angular-youtube-embed@1.1.1 node_modules\angular-youtube-embed
└── angular@1.5.3


how to sort this issue?

**Comment by aluanhaddad** [comment]
For what it's worth, I use jspm. After using bower for a while, I came to the conclusion that it is pretty useless.
