### ISSUE TITLE
Unable to use this under ionic modal.

### ISSUE THREAD

**Issue by niyando** [brandly/angular-youtube-embed#97]
Hi,
Thanks for this awesome tool. I am trying to use this inside a modal box, specifically ionicModal service http://ionicframework.com/docs/api/service/$ionicModal/ . But it doesn't work inside the modal. It works if I put it on parent template.

error i get:
```js
TypeError: Cannot set property 'width' of null
    at P.g.$ (www-widgetapi.js:79)
    at angular-youtube-embed.js:238
```

**Comment by brandly** [comment]
can you recreate the issue in a [JSFiddle](http://jsfiddle.com/) or something similar?

**Comment by niyando** [comment]
I have setup a plunkr that demonstrates this issue. Let me know if you have more questions. Would be happy to help. 
http://run.plnkr.co/PyW6AKbcZF3WsE7Y/

**Comment by brandly** [comment]
Thanks for the plnkr! this seems to be some odd DOM manipulation caused by `ionicModal`. I put the [more readable source](https://github.com/brandly/angular-youtube-embed/blob/d654e43da6da39e07bdd96a85664993da63a2ac6/src/angular-youtube-embed.js) into your plnkr to debug. 

It looks like [the link function](https://github.com/brandly/angular-youtube-embed/blob/d654e43da6da39e07bdd96a85664993da63a2ac6/src/angular-youtube-embed.js#L130) gets called for both the video inside the modal and the video outside as soon as the page loads. The `TypeError: Cannot set property 'width' of null` appears to actually happen to the video outside the modal, because they're removing that content from the DOM or something, so when [we call `player.setSize`](https://github.com/brandly/angular-youtube-embed/blob/d654e43da6da39e07bdd96a85664993da63a2ac6/src/angular-youtube-embed.js#L238), even tho _we_ have a reference to `scope.player`, it looks like it's not in the DOM anymore.

As for the modal video not showing up, I believe it's due to `ionicModal` binding the view to scope before the view is actually in the DOM. then, when we create a YouTube player and [give it the `id` of the element](https://github.com/brandly/angular-youtube-embed/blob/d654e43da6da39e07bdd96a85664993da63a2ac6/src/angular-youtube-embed.js#L175), it's unable to find that element in the DOM.

It's not pretty, but a workaround I found is to set the video id _after_ the modal is in the DOM. This would look something like

```js
    $scope.openLocationsModal = function() {
      $scope.locationsModal.show();
      $timeout(function () {
        // Wait until after showing modal to set the video id
        $scope.theBestVideo = 'sMKoNBRZM1M'
      }, 300)
    };
```

[You can view the working code here](http://plnkr.co/edit/YnrsTJrIccPnymsbb4Ai?p=preview) :star2:

**Comment by niyando** [comment]
Thanks for such a quick turnaround. This fix indeed works. :+1:
