### ISSUE TITLE
Background Playing when app is "paused"

### ISSUE THREAD

**Issue by danielpflood** [brandly/angular-youtube-embed#98]
Failed submission to Android Store due to: 

<pre>
Your submission has been rejected for enabling background playing of YouTube videos in violation of the YouTube API Terms of Service.
</pre>

Should this happen automatically using this plugin? If not does anyone have a recommendation for how to achieve this with an Ionic app?

I am able to detect pausing from the controller with this: 
<pre>
<code>
document.addEventListener("pause", function() {
    console.log("The application is pausing");
}, false);
</code> 
</pre>
But I am not sure how to obtain the video-player object in order to call its pause method.  Thanks for your help.

**Comment by danielpflood** [comment]
I was able to retrieve the player with this:
<pre>
<code>
    var ytplayer_window = document.getElementById("unique-youtube-embed-id-1").contentWindow;
    var myPlayer = ytplayer_window.yt.player.getPlayerByElement(ytplayer_window.player);
</code>
</pre>

**Comment by brandly** [comment]
hey daniel! instead of digging into the DOM like that, you can also [give the `<youtube-video>` a `player` reference](https://github.com/brandly/angular-youtube-embed#player-functions), which it will assign the player to.

also, all event handlers [get handed the relevant `player`](https://github.com/brandly/angular-youtube-embed#events-and-player-controls), so you can access it there as well.

good luck with the Android Store!
